### ISSUE TITLE
Add networks to sdx_global.cfg

### ISSUE THREAD

**Issue by TribuneX** [h2020-endeavour/endeavour#22]
In order to build the mininet topology from the cfg files, the advertised networks by each participant should be also stated in the config. 

Suggestion:

```
"a1": {
            "Ports": [
                {
                    "Id": 5,
                    "MAC": "08:00:27:89:3b:9f",
                    "IP": "172.0.0.1",
                    "Networks": ["100.0.0.0/24", "110.0.0.0/24"]
                }
            ],
```

This will allow to substitute this line per participant in the simple_sdx.py from the config:
 networks=['100.0.0.0/24', '110.0.0.0/24']

**Comment by ederlf** [comment]
@TribuneX  I thought about it last night and I am not so sure about it now. Because it might have meaning to create the mininet topology, but for the iSDX code  (so far) it has no use. 

As the sdx_global.cfg contains information required to configure the fabric, i wonder if adding a new field only for creation of test topologies would not add "noise" to the config file.

in my opinion, it is interesting to create the mininet topo with the sdx_global.cfg, but i would put the announcements in a separate file.

**Comment by TribuneX** [comment]
Just discovered that there is already a mininet.cfg which includes this information. I pushed a new master version which uses the networks defined in the mininet.cfg for building the topology.
