### ISSUE TITLE
Setup a Vagrant file to produce a working dev environment

### ISSUE THREAD

**Issue by mcanini** [h2020-endeavour/endeavour#3]

**Comment by ederlf** [comment]
It is almost done. Since it depends on iSDX scripts, I will push it when the code is imported to the endeavour repository.

**Comment by ederlf** [comment]
This commit ba908dabd052920c822d7d635f952a2c33c0f822  brings the basic virtual machine for the development of the Endeavour platform. It is basically the iSDX VM with some minor changes regarding the setup.

Instead of using the iSDX repository as a shared repository, it clones the source from the Endeavour organisation and uses Vagrant vm provision to issue inline commands that run the iSDX setup scripts.

You might want to check if there is something you want to add.  If there are not many requests, we can add it just adding some inline commmands to the Vagrantfile. Otherwise, we can create a setup folder in our repository with installation scripts, similar to iSDX.

If there are no comments until tomorrow, I will close the task.

**Comment by mcanini** [comment]
@thanhucl Please test this and report if it works for you. If so we will close the issue.

**Comment by thanh-nguyen-dang** [comment]
I test vagrant file. I can do vagrant up to do provisioning. There are some warning message such as stdin is not installed. But it does not block the provisioning.
After provisioning I can start the VM and try an example of iSDX. I can go through the example.

**Comment by TribuneX** [comment]
I added the proxy configuration to the Vagrantfile in order to work in our testbed environment.
