### ISSUE TITLE
Decide on how out to integrate the ARP-Proxy functionality of UMBRELLA

### ISSUE THREAD

**Issue by mcanini** [h2020-endeavour/endeavour#5]

**Comment by marchiesa** [comment]
ARP PROXY: The iSDX proxy will be responsible for translating virtual IP next-hops, assigned to prefixes belonging to the same Forwarding Equivalence Class (FEC), to a Virtual destination MAC, which encodes the IXP ports that are announcing an IP prefix that contains the destination IP of a packet. It will also translates legacy IP next-hops to legacy MAC addresses. 

FORWARDING: The iSDX forwarding tables translates the VMAC of a packet to the legacy MAC address of its IXP outgoing port. The Umbrella forwarding table translates legacy MAC addresses to encoded paths within the IXP fabric.

**Comment by ederlf** [comment]
@marchiesa 
I just thought in a different sequence.

**Comment by ederlf** [comment]
I had a different idea for the sequence in the tables:

For incoming packets in the fabric, the pipeline can be:

```
main-in -> outbound (if there is an outbound policy) -> load balance -> umbrella-in
```

Here, the packet is processed normally by the known iSDX processing. It goes through a load balancing table to decide the port it will leave the incoming edge. Finally, it reaches the umbrella-in table where the path is encoded.

For outgoing packets:

```
umbrella-out -> inbound -> main-out
```

At the umbrella-out table the iSDX mac is rewritten. Then it goes to the inbound where any policy is applied and finally goes to the main-out where the VMAC becomes the real MAC address. 

The idea is the following:

For the umbrella encoding we need to know the port the packet will leave the
incoming edge and the next-hop. The next-hop, so far is given directly by the 
destination MAC. Considering that the iSDX VMAC encodes the next hop information in the last bits of the MAC(defined by configuration), we can match on this information to encode the path defined by umbrella.

For the load balancing, the initial idea is to use the metadata field, so we
can match on the dp_id of the destination core.

On the exit edge, it works because the inbound policy only matches on the next hop (can't think in a case it would need the rest, reachability, of the VMAC), which can be easily translated from umbrella, because we know the path. 

Does it makes sense?

**Comment by mcanini** [comment]
@ederlf We discussed that inbound policy needs to execute at the ingress edge switch rather than at the outgoing one.
